function y = butterworth_lowpass(signal,cutoff,Fs)
%BUTTERWORTH_LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 08-Aug-2016 16:53:11

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
  % Sampling Frequency

N  = 10;     % Order
Fc = cutoff;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
sz=size(signal);
y=zeros(sz);
for i=1:sz(1)
    y(i,:)=filtfilt(Hd.sosMatrix,Hd.ScaleValues,signal(i,:));
end
% [EOF]
